
package com.zl.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloService", targetNamespace = "http://zl.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://zl.com/", className = "com.zl.client.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://zl.com/", className = "com.zl.client.SayHelloResponse")
    @Action(input = "http://zl.com/HelloService/sayHelloRequest", output = "http://zl.com/HelloService/sayHelloResponse")
    public void sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello2", targetNamespace = "http://zl.com/", className = "com.zl.client.SayHello2")
    @ResponseWrapper(localName = "sayHello2Response", targetNamespace = "http://zl.com/", className = "com.zl.client.SayHello2Response")
    @Action(input = "http://zl.com/HelloService/sayHello2Request", output = "http://zl.com/HelloService/sayHello2Response")
    public String sayHello2(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
